"""empty message

Revision ID: 1451bd9246b4
Revises: 
Create Date: 2023-06-24 10:31:47.709147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1451bd9246b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_groups', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
