"""empty message

Revision ID: 14b0130ed411
Revises: 13eb91b34f56
Create Date: 2023-05-17 20:48:57.016395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b0130ed411'
down_revision = '13eb91b34f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.drop_column('goal3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal3', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
