"""empty message

Revision ID: 71afdc4acf98
Revises: 443b1ac57b38
Create Date: 2023-07-09 15:56:35.683217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71afdc4acf98'
down_revision = '443b1ac57b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('positions', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('positions')

    # ### end Alembic commands ###
